[workspace]
members = [
    "crates/core",
    "crates/packet-parser",
    "crates/pcap-shim",
    "crates/utils",
    "crates/config",
    "crates/af-xdp",
    "crates/dpdk",
    "crates/dataplane",
    "aegis",
]
resolver = "2"
